// A. Diagrama de Caso de Uso: focado na interação do motorista com as funcionalidades principais.
@startuml
left to right direction
actor "Cliente" as C

rectangle "AutoTech Care System" {
  usecase "Cadastrar Veículo" as UC1
  usecase "Registrar Manutenção" as UC2
  usecase "Realizar Diagnóstico (IA)" as UC3
  usecase "Consultar Histórico" as UC4
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4
@enduml

//www.plantuml.com/plantuml/dpng/LSu_JaCn3CVnFQUmtWH31rfcr2eCCB3mXztACscaF4UodG4Gfs5WOkeHSZ52wKFjzfNoqIzUgw5OdRBBz69W1IJ5hS6OX8AbmWw35O71vqHiD00gUET-Nv5Z9XWsrSeZXIru58A7LpMQ1dXt05Kfe7RYSKGrGO5dQj-XvhBVUV8Nn-gUOlfJTyZLYDjN-vpbybHYJcyTNYUCt7PgAHGukzsS7_JgvFV2MhDrVjFtsquwFhXBz-6SXyNYQd_CNCl_MitLwPfuh5F-0G00
