# Diagrama de Caso de Uso: 

Focado na interação do motorista com as funcionalidades principais.

@startuml
left to right direction
actor "Cliente (Motorista)" as C

rectangle "AutoTech Care System" {
  usecase "Cadastrar Veículo" as UC1
  usecase "Solicitar Diagnóstico IA" as UC2
  usecase "Gerenciar Perfil de Usuário" as UC3
  usecase "Visualizar Histórico de Consultas" as UC4
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4
@enduml
