// B. Diagrama de Classes: utilizando a hierarquia que definimos (Herança e Interface).
  @startuml
abstract class Carro {
    # String modelo
    # String placa
    + Carro(modelo, placa)
}

interface IVerificavel {
    + realizarCheckup()
}

class CarroBateria {
    - int vidaUtilMeses
    + realizarCheckup()
}

class CarroMotor {
    - double nivelOleo
    + realizarCheckup()
}

Carro <|-- CarroBateria
Carro <|-- CarroMotor
IVerificavel <|.. CarroBateria
IVerificavel <|.. CarroMotor
@enduml
